### ISSUE TITLE
Fix Background Images.

### ISSUE THREAD

**Issue by Kerpackie** [NadineLikeADragon/LibraryApp#11]
Precursory note, TODO's will be left within the codebase with the next PR indicating you will need to fix the background image.

The line:

```this.BackgroundImage = global::PersonalLibraryApp.Properties.Resources.AddItem_Background;```

Is not supported within .NET 6 and above, reapplying the background image using the tooling should fix it.

**Comment by MIDAS74** [comment]
gonna close this, Nadine doesn't seem to mind about the images, and tbh neither do I. Replaced with blank teal background. Thanks for the help man, I'll try not to ask for a repo recovery ever again.
